### ISSUE TITLE
Incongruencia en los métodos toTemperatura

### ISSUE THREAD

**Issue by alu0100783230** [ULL-ESIT-GRADOII-PL/mocha-y-chai-ele-daniel-1#1]
@EleDiaz 

Las funciones no utilizan el parámetro value sino su valor interno

```
toFahrenheit: function(value) {
   return ((this.toCelsius(this.valor) * 9/5)+32);
}
```

**Comment by EleDiaz** [comment]
Lo corrijo en un momento y y cierro el issue #1

**Comment by EleDiaz** [comment]
he encontrado más fallos en esos ficheros :warning:

**Comment by EleDiaz** [comment]
af9440578481161c67ea2f9bb1eba2d854adddfd
